name: Publish documentation

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Fetch all git branches
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn docs
      - uses: docker://malept/gha-gh-pages:1.3.0
        with:
          docsPath: docs
          gitCommitMessage: "Publish [skip ci]"
          showUnderscoreFiles: true
          versionDocs: true
        env:
          GH_PAGES_SSH_DEPLOY_KEY: ${{ secrets.DOCS_SSH_DEPLOY_KEY }}
